use_frameworks!

platform :ios, '9.0'

target 'test11_Example' do
  pod 'test11', :path => '../'

  target 'test11_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
